"""Export routes — PDF and DOCX download."""

from __future__ import annotations

import io
import logging
from datetime import datetime, timezone

from bson import ObjectId
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse

from app.db.mongodb import get_database
from app.routes.projects import _assert_project_access

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/projects/{project_id}/export", tags=["Export"])
UTC = timezone.utc


async def _load_all_reports(db, project_id: str) -> dict:
    report_docs = await db.generated_reports.find(
        {"project_id": ObjectId(project_id)}
    ).to_list(None)

    result: dict = {}
    for doc in report_docs:
        version_doc = await db.report_versions.find_one({"_id": doc.get("current_version_id")})
        if version_doc:
            result[doc["report_type"]] = version_doc["content_snapshot"]
    return result


def _report_markdown(report_type: str, content: dict) -> str:
    if content.get("markdown"):
        return content["markdown"]
    if content.get("overview"):
        return content["overview"].get("content", "")
    return str(content)


def _reports_to_html(project_title: str, reports: dict) -> str:
    sections: list[str] = []
    for report_type, content in reports.items():
        title = report_type.replace("_", " ").title()
        body = _report_markdown(report_type, content)
        sections.append(f"<h1>{title}</h1><pre style='white-space:pre-wrap;font-family:inherit'>{body}</pre>")

    html_body = "\n".join(sections)
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 900px; margin: 40px auto; color: #1a1a2e; line-height: 1.7; }}
  h1 {{ color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 8px; margin-top: 40px; }}
</style>
</head>
<body>
<h1>{project_title}</h1>
<p style="color:#6b7280;">Generated by Planify · {datetime.now(UTC).strftime('%B %d, %Y')}</p>
{html_body}
</body>
</html>"""


@router.get("/pdf", summary="Export all reports as PDF")
async def export_pdf(request: Request, project_id: str):
    user = request.state.user
    db = get_database()

    project = await _assert_project_access(project_id, user, db)
    reports = await _load_all_reports(db, project_id)
    if not reports:
        raise HTTPException(status_code=404, detail="No reports generated yet.")

    html_content = _reports_to_html(project.get("title", "Project"), reports)
    try:
        from weasyprint import HTML  # type: ignore
    except OSError as exc:
        raise HTTPException(
            status_code=503,
            detail=f"PDF generation unavailable: {exc}",
        ) from exc

    pdf_bytes = HTML(string=html_content).write_pdf()
    filename = f"planify-{project.get('title', 'report').replace(' ', '_').lower()}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/docx", summary="Export all reports as DOCX")
async def export_docx(request: Request, project_id: str):
    user = request.state.user
    db = get_database()

    project = await _assert_project_access(project_id, user, db)
    reports = await _load_all_reports(db, project_id)
    if not reports:
        raise HTTPException(status_code=404, detail="No reports generated yet.")

    from docx import Document  # type: ignore

    doc = Document()
    doc.add_heading(project.get("title", "Project Reports"), level=0)
    doc.add_paragraph(f"Generated by Planify · {datetime.now(UTC).strftime('%B %d, %Y')}")

    for report_type, content in reports.items():
        doc.add_heading(report_type.replace("_", " ").title(), level=1)
        doc.add_paragraph(_report_markdown(report_type, content))

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    filename = f"planify-{project.get('title', 'report').replace(' ', '_').lower()}.docx"
    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
