"""
Export routes.

GET /api/projects/{id}/export/pdf   — download all reports as a PDF
GET /api/projects/{id}/export/docx  — download all reports as a DOCX
"""
from __future__ import annotations

import io
import logging
from datetime import datetime, timezone

from bson import ObjectId
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse

from app.db.mongodb import get_database
from app.routes.projects import _assert_project_access

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/projects/{project_id}/export", tags=["Export"])

UTC = timezone.utc


async def _load_all_reports(db, project_id: str) -> dict:
    """Fetch all 4 report contents for a project."""
    report_docs = await db.generated_reports.find(
        {"project_id": ObjectId(project_id)}
    ).to_list(None)

    result: dict = {}
    for doc in report_docs:
        version_doc = await db.report_versions.find_one({"_id": doc.get("current_version_id")})
        if version_doc:
            result[doc["report_type"]] = version_doc["content_snapshot"]
    return result


def _reports_to_html(project_title: str, reports: dict) -> str:
    """Render all reports as a single styled HTML document."""
    sections: list[str] = []

    prd = reports.get("prd", {})
    if prd:
        sections.append(f"<h1>Product Requirements Document</h1>")
        sections.append(f"<h2>{prd.get('overview', {}).get('title', '')}</h2>")
        sections.append(f"<p>{prd.get('overview', {}).get('content', '')}</p>")

        if prd.get("goals"):
            sections.append("<h3>Goals</h3><ul>")
            sections.extend(f"<li>{g}</li>" for g in prd["goals"])
            sections.append("</ul>")

        if prd.get("user_stories"):
            sections.append("<h3>User Stories</h3><ul>")
            sections.extend(f"<li>{s}</li>" for s in prd["user_stories"])
            sections.append("</ul>")

        if prd.get("functional_requirements"):
            sections.append("<h3>Functional Requirements</h3><ul>")
            sections.extend(f"<li>{r}</li>" for r in prd["functional_requirements"])
            sections.append("</ul>")

        sections.append(f"<p><strong>MVP:</strong> {prd.get('mvp_definition', '')}</p>")

    feasibility = reports.get("feasibility", {})
    if feasibility:
        sections.append("<hr/><h1>Feasibility Assessment</h1>")
        sections.append(f"<p><strong>Complexity:</strong> {feasibility.get('complexity_signal', '').upper()}</p>")
        sections.append(f"<p>{feasibility.get('technical_approach', '')}</p>")
        if feasibility.get("key_risks"):
            sections.append("<h3>Key Risks</h3><ul>")
            sections.extend(f"<li>{r}</li>" for r in feasibility["key_risks"])
            sections.append("</ul>")

    roi = reports.get("roi", {})
    if roi:
        sections.append("<hr/><h1>ROI & Financial Model</h1>")
        sections.append(f"<p><strong>Development Cost:</strong> {roi.get('development_cost_range', '')}</p>")
        sections.append(f"<p><strong>Infrastructure:</strong> {roi.get('infrastructure_cost_estimate', '')}</p>")
        sections.append(f"<p><strong>Team Cost:</strong> {roi.get('team_cost_estimate', '')}</p>")

    roadmap = reports.get("roadmap", {})
    if roadmap:
        sections.append("<hr/><h1>Project Roadmap</h1>")
        sections.append(f"<p><strong>Total Timeline:</strong> {roadmap.get('total_timeline_weeks', '?')} weeks</p>")
        for phase in roadmap.get("phases", []):
            sections.append(f"<h3>{phase.get('phase_name', '')} ({phase.get('duration_weeks', '?')} weeks)</h3>")
            sections.append(f"<p>{phase.get('description', '')}</p>")
            if phase.get("milestones"):
                sections.append("<ul>")
                sections.extend(f"<li>{m}</li>" for m in phase["milestones"])
                sections.append("</ul>")

    html_body = "\n".join(sections)
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 900px; margin: 40px auto; color: #1a1a2e; line-height: 1.7; }}
  h1 {{ color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 8px; margin-top: 40px; }}
  h2 {{ color: #4f46e5; }}
  h3 {{ color: #6d28d9; }}
  hr {{ border: none; border-top: 1px solid #e5e7eb; margin: 32px 0; }}
  li {{ margin: 4px 0; }}
  p {{ margin: 8px 0; }}
</style>
</head>
<body>
<h1 style="font-size: 2em; border: none;">{project_title}</h1>
<p style="color: #6b7280;">Generated by Planify · {datetime.now(UTC).strftime('%B %d, %Y')}</p>
{html_body}
</body>
</html>"""


@router.get("/pdf", summary="Export all reports as PDF")
async def export_pdf(request: Request, project_id: str):
    user = request.state.user
    db = get_database()

    project = await _assert_project_access(project_id, user, db)
    reports = await _load_all_reports(db, project_id)

    if not reports:
        raise HTTPException(status_code=404, detail="No reports generated yet. Run the AI workflow first.")

    html_content = _reports_to_html(project.get("title", "Project"), reports)

    # Render PDF in memory (lazy import so server starts without system pango)
    try:
        from weasyprint import HTML  # type: ignore
    except OSError as exc:
        raise HTTPException(
            status_code=503,
            detail=f"PDF generation unavailable — missing system libraries (Pango/GObject). Install via `brew install pango`. Details: {exc}",
        ) from exc

    pdf_bytes = HTML(string=html_content).write_pdf()
    filename = f"planify-{project.get('title', 'report').replace(' ', '_').lower()}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/docx", summary="Export all reports as DOCX")
async def export_docx(request: Request, project_id: str):
    user = request.state.user
    db = get_database()

    project = await _assert_project_access(project_id, user, db)
    reports = await _load_all_reports(db, project_id)

    if not reports:
        raise HTTPException(status_code=404, detail="No reports generated yet. Run the AI workflow first.")

    # Lazy import
    from docx import Document  # type: ignore
    from docx.shared import RGBColor  # type: ignore

    doc = Document()
    doc.core_properties.author = "Planify AI"

    title = doc.add_heading(project.get("title", "Project Reports"), level=0)
    title.runs[0].font.color.rgb = RGBColor(0x7C, 0x3A, 0xED)
    doc.add_paragraph(f"Generated by Planify · {datetime.now(UTC).strftime('%B %d, %Y')}")

    prd = reports.get("prd", {})
    if prd:
        doc.add_heading("Product Requirements Document", level=1)
        doc.add_heading(prd.get("overview", {}).get("title", ""), level=2)
        doc.add_paragraph(prd.get("overview", {}).get("content", ""))
        if prd.get("goals"):
            doc.add_heading("Goals", level=3)
            for g in prd["goals"]:
                doc.add_paragraph(g, style="List Bullet")
        if prd.get("user_stories"):
            doc.add_heading("User Stories", level=3)
            for s in prd["user_stories"]:
                doc.add_paragraph(s, style="List Bullet")
        if prd.get("functional_requirements"):
            doc.add_heading("Functional Requirements", level=3)
            for r in prd["functional_requirements"]:
                doc.add_paragraph(r, style="List Bullet")
        doc.add_paragraph(f"MVP Definition: {prd.get('mvp_definition', '')}")

    feasibility = reports.get("feasibility", {})
    if feasibility:
        doc.add_page_break()
        doc.add_heading("Feasibility Assessment", level=1)
        doc.add_paragraph(f"Complexity: {feasibility.get('complexity_signal', '').upper()}")
        doc.add_paragraph(feasibility.get("technical_approach", ""))
        if feasibility.get("key_risks"):
            doc.add_heading("Key Risks", level=3)
            for r in feasibility["key_risks"]:
                doc.add_paragraph(r, style="List Bullet")

    roi = reports.get("roi", {})
    if roi:
        doc.add_page_break()
        doc.add_heading("ROI & Financial Model", level=1)
        doc.add_paragraph(f"Development Cost: {roi.get('development_cost_range', '')}")
        doc.add_paragraph(f"Infrastructure: {roi.get('infrastructure_cost_estimate', '')}")
        doc.add_paragraph(f"Team Cost: {roi.get('team_cost_estimate', '')}")

    roadmap = reports.get("roadmap", {})
    if roadmap:
        doc.add_page_break()
        doc.add_heading("Project Roadmap", level=1)
        doc.add_paragraph(f"Total Timeline: {roadmap.get('total_timeline_weeks', '?')} weeks")
        for phase in roadmap.get("phases", []):
            doc.add_heading(f"{phase.get('phase_name', '')} ({phase.get('duration_weeks', '?')} weeks)", level=2)
            doc.add_paragraph(phase.get("description", ""))
            for m in phase.get("milestones", []):
                doc.add_paragraph(m, style="List Bullet")

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)

    filename = f"planify-{project.get('title', 'report').replace(' ', '_').lower()}.docx"
    return StreamingResponse(
        buf,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
